<Project>

  <PropertyGroup>
    <Authors>Akeoott</Authors>
    <Version Condition=" '$(Version)' == '' ">1.0.0-local</Version>

    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>LGPL-3.0-or-later</PackageLicenseExpression>

    <PackageProjectUrl>https://github.com/Akeoott/ZenMonitor.Core</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Akeoott/ZenMonitor.Core.git</RepositoryUrl>

    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="System" />
    <Using Include="System.Runtime.Versioning" />
  </ItemGroup>

</Project>