name: Prep-Publish

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  suggest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PIPELINE_PAT }}

      - name: Get next version
        uses: smlx/ccv@7318e2f25a52dcd550e75384b84983973251a1f8
        id: ccv

      - name: Generate changelog
        uses: orhun/git-cliff-action@f50e11560dce63f7c33227798f90b924471a88b5
        id: cliff
        with:
          args: --unreleased --strip all

      - name: Create Draft Release and Tag
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda
        with:
          name: "Release ${{ steps.ccv.outputs.next-version }}"
          tag_name: ${{ steps.ccv.outputs.next-version }}
          body: ${{ steps.cliff.outputs.content }}
          draft: true
          token: ${{ secrets.RELEASE_PIPELINE_PAT }}
