name: Publish NuGet Package

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  validate-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --output ./artifacts /p:PackageVersion=${{ github.event.release.tag_name }} --no-restore

      - name: NuGet Login (OIDC)
        uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841
        id: login
        with:
          user: "Akeoott"

      - name: Push Package to NuGet.org
        run: |
          dotnet nuget push "./artifacts/*.nupkg" \
            --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" \
            --source "https://nuget.org" \
            --skip-duplicate
